### ISSUE TITLE
Repo URL gives 404

### ISSUE THREAD

**Issue by sebix** [manfred-kaiser/python-enhancements#17]
The URL of this Repo (https://enhancements.readthedocs.io/de/master/) gives an error 404, should probably be https://enhancements.readthedocs.io/en/latest/
![image](https://user-images.githubusercontent.com/199050/142457446-8ee14c59-2ce8-4255-a028-3ddadd65c524.png)

**Comment by manfred-kaiser** [comment]
:+1:  Thanks for the bug report. I have fixed the url.
